### ISSUE TITLE
Top UI button not shown

### ISSUE THREAD

**Issue by Compound-codes** [python-nerd-3/crystal-coves-2#6]
![Screen Shot 2024-02-29 at 19 50 15](https://github.com/python-nerd-3/crystal-coves-2/assets/68404606/72a41a0b-b28c-41fc-8a2a-ecbabb9d54e0)

The top UI button is not shown fully unless the user is in fullscreen.
(Google Chrome)

**Comment by python-nerd-3** [comment]
monitor issue
