### ISSUE TITLE
Backpack scroll is being goofy.

### ISSUE THREAD

**Issue by Compound-codes** [python-nerd-3/crystal-coves-2#7]
https://github.com/python-nerd-3/crystal-coves-2/assets/68404606/992a36c0-e0e0-430a-8f6c-62713bff4f9c

goofy

looks like there's two separate scrollbars, but the one inside the canvas can scroll a lot past where it should be able to scroll

**Comment by Compound-codes** [comment]
![Screen Shot 2024-02-29 at 20 26 27](https://github.com/python-nerd-3/crystal-coves-2/assets/68404606/987ead45-8ea4-43fc-b445-53180b4ab7cb)
Also, this can cause overlap within text.

**Comment by Compound-codes** [comment]
like i don't mean there's two shown separate scrollbars, it acts like a second scrollbar

**Comment by python-nerd-3** [comment]
implemented a fix in 2.0.2
