### ISSUE TITLE
Zero ores when sold

### ISSUE THREAD

**Issue by Compound-codes** [python-nerd-3/crystal-coves-2#9]
![Screen Shot 2024-02-29 at 20 17 17](https://github.com/python-nerd-3/crystal-coves-2/assets/68404606/69e8c3aa-e334-4028-85b0-39719c573952)

I sold this ore, so it has 0 as a counter, plus I bought 2 dynamite with it, although the two dynamite never showed up in my inventory. 🤔

**Comment by Compound-codes** [comment]
Maybe make it more clear that you can see the store-bought items by right-clicking the store.

**Comment by python-nerd-3** [comment]
this works as intended, you can see your items by right clicking a block

**Comment by Compound-codes** [comment]
What about the 0 ore problem?

**Comment by python-nerd-3** [comment]
0 ores works as intended

**Comment by Compound-codes** [comment]
I see.
